#line 2 "lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 103
#define YY_END_OF_BUFFER 104
static yyconst short int yy_accept[729] =
    {   0,
        0,    0,  104,  102,  100,    1,  102,  102,   93,   94,
      102,   92,  102,   96,   96,   87,   88,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,   90,   91,
      100,    0,   95,    0,    0,   98,    0,   96,   96,    2,
        0,    0,    0,   96,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,   95,    0,    0,   96,    0,

       99,   97,    0,   97,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,   89,  101,  101,  101,  101,  101,  101,  101,   76,
       46,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
        0,  101,   82,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,   53,  101,  101,  101,  101,   81,
      101,  101,  101,  101,   62,  101,  101,  101,  101,  101,
      101,  101,   42,  101,  101,    0,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,   43,   72,   63,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
       77,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,   86,  101,  101,  101,  101,  101,
      101,  101,  101,  101,   83,  101,  101,  101,  101,  101,
       71,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,   28,  101,  101,  101,  101,
      101,  101,  101,  101,   54,  101,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,   85,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,   56,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,   52,
      101,  101,  101,   47,  101,  101,  101,   73,  101,  101,
      101,  101,  101,  101,  101,  101,  101,   84,  101,  101,
       64,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,   67,  101,  101,

      101,  101,  101,  101,  101,  101,  101,   33,   37,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,   34,  101,  101,
      101,  101,  101,  101,   58,  101,  101,  101,  101,  101,
       55,  101,  101,  101,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,  101,
       69,  101,  101,  101,  101,   80,  101,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,   60,  101,
      101,  101,   49,  101,    8,  101,  101,  101,  101,  101,
      101,  101,  101,   38,  101,  101,  101,  101,   41,    7,

      101,  101,   48,  101,  101,  101,  101,  101,  101,    5,
      101,  101,  101,  101,  101,   31,  101,  101,  101,  101,
      101,   50,  101,  101,  101,   32,  101,  101,  101,  101,
      101,  101,   39,  101,   27,  101,  101,   45,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,  101,    4,
      101,   44,   59,  101,  101,  101,  101,   13,  101,   12,
      101,   68,  101,  101,  101,   26,   66,  101,  101,  101,
      101,  101,  101,  101,  101,  101,  101,  101,   29,  101,
      101,    9,   57,  101,  101,  101,   14,   11,  101,  101,
      101,  101,  101,  101,  101,  101,  101,   10,  101,  101,

      101,  101,  101,   51,  101,  101,  101,  101,  101,  101,
      101,   40,    3,  101,  101,  101,  101,  101,  101,  101,
      101,  101,   65,  101,  101,  101,  101,  101,  101,  101,
        6,  101,  101,  101,  101,  101,  101,   35,  101,  101,
       61,  101,  101,   19,  101,  101,  101,  101,  101,  101,
      101,   78,  101,  101,  101,  101,  101,  101,  101,  101,
      101,   20,  101,  101,  101,   75,   25,   36,  101,  101,
      101,  101,  101,  101,  101,  101,  101,   30,  101,  101,
       79,   17,  101,  101,  101,  101,  101,  101,  101,  101,
       74,  101,  101,  101,   18,  101,  101,  101,  101,  101,

      101,  101,  101,  101,  101,  101,   15,  101,  101,  101,
      101,  101,  101,   23,  101,   16,  101,  101,   70,  101,
       24,  101,  101,  101,   21,  101,   22,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,    1,
       18,    1,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
        1,   19,    1,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,    1,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    3,    3,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst short int yy_base[733] =
    {   0,
        0,    0,  792,  793,  789,  793,   44,  787,  793,  793,
       40,  793,   44,   41,   44,  793,  793,    0,  757,   36,
       32,   43,   41,  753,  766,   36,   55,  765,   60,   48,
      752,  763,  742,   65,   66,   58,  748,  752,  793,  793,
      778,   69,  793,  102,  776,  793,   89,  793,   77,  793,
      775,   87,   98,  102,    0,  734,  751,  741,  745,  741,
      749,  745,  731,  735,  736,  744,  745,  731,  724,  724,
       69,  112,  737,  729,  719,  715,  724,  715,   86,  723,
      721,  715,   90,  724,   94,  717,  717,  715,  720,  713,
      718,  706,   30,  723,  710,  124,  147,  126,  119,  740,

      793,  122,  133,  138,  721,  705,  716,  716,  703,  705,
      129,  700,  695,  695,  692,  699,  708,  695,  689,  693,
      692,  793,  698,  689,  692,  689,  693,  680,  695,    0,
        0,  697,  689,  678,  676,  675,  675,  675,  683,  671,
      686,  666,  672,  671,  683,  673,  670,  678,  673,  677,
      145,  655,    0,  108,  668,  118,  673,  656,  662,  663,
      141,  669,  654,  667,  651,  647,  651,  657,  649,  665,
      645,  128,  661,  650,    0,  135,  657,  645,  654,    0,
      654,  653,  652,  630,    0,  635,  641,  650,  636,  640,
      645,  630,    0,  634,  632,  159,  627,  624,  626,  638,

      622,  621,  622,  148,  627,  633,  636,  627,  626,  619,
      632,    0,  616,    0,  622,  615,  628,  623,  616,  610,
      607,  615,  614,  614,  612,  606,  614,  600,  599,  601,
        0,  143,  596,  609,  598,  607,  586,  585,  584,  154,
      599,  603,  583,  590,  584,  602,  577,  586,  591,  579,
      593,  592,  578,  575,    0,  569,  579,  573,  588,  581,
      574,  573,  569,  572,    0,  566,  579,  582,  579,  561,
        0,  554,  559,  559,  562,  571,  572,  561,  559,  564,
      562,  547,  555,  565,  561,    0,  565,  550,  559,  164,
      168,  549,  542,  554,  542,  553,  538,  548,  548,  531,

      549,  530,  160,  548,  535,  529,  530,  536,  533,  535,
      526,  528,  539,  528,  536,  532,  534,  533,  528,  530,
      516,  513,  520,  529,    0,  517,  515,  508,  516,  512,
      508,  506,  510,  502,  504,  516,  508,  505,  517,  106,
      502,    0,  511,  500,  502,  493,  511,  491,  488,  494,
      503,  502,  497,  496,  163,  492,  484,  497,  492,    0,
      481,  490,  497,    0,  478,  484,  490,  165,  476,  467,
      469,  486,  471,  484,  463,  467,  468,    0,  480,  481,
      477,  473,  461,  460,  478,  453,  476,  457,  462,  459,
      458,  458,  459,  467,  464,  456,  445,    0,  457,  447,

      450,  457,  455,  441,  455,  444,  457,    0,    0,  454,
      440,  450,  451,  444,  427,  427,  435,  444,  447,  442,
      431,  431,  441,  439,  439,  436,  429,    0,  418,  423,
      417,  430,  415,  427,  415,  413,  411,  425,  409,  412,
        0,  422,  405,  423,  419,  414,  407,  410,  400,  399,
      410,  405,  391,  394,  389,  388,  411,  397,  405,  404,
        0,  388,  389,  388,  402,    0,  386,  383,  390,  392,
      388,  381,  379,  378,  382,  386,  379,  378,    0,  387,
      372,  389,    0,  369,    0,  387,  368,  385,  383,  369,
      362,  363,  376,    0,  360,  374,  359,  358,    0,    0,

      373,  355,    0,  360,  355,  363,  351,  350,  358,    0,
      359,  366,  361,  364,  348,    0,  343,  347,  343,  346,
      347,    0,  344,  342,  337,    0,  337,  353,  139,  334,
      336,  333,    0,  348,    0,  344,  343,    0,  327,  341,
      319,  335,  334,  323,  338,  320,  333,  335,  336,    0,
      322,    0,    0,  330,  331,  320,  327,  175,  313,    0,
      312,    0,  328,  323,  326,    0,    0,  307,  312,  309,
      320,  300,  305,  309,  314,  309,  297,  313,    0,  314,
      309,    0,    0,  298,  297,  306,  177,    0,  307,  305,
      290,  292,  301,  291,  303,  298,  301,    0,  289,  286,

      290,  293,  278,    0,  293,  281,  270,  278,  277,  286,
      285,    0,    0,  275,  272,  267,  274,  273,  281,  258,
      273,  259,    0,  275,  258,  272,  257,  273,  261,  250,
        0,   33,   71,  120,  167,  159,  180,    0,  167,  183,
        0,  171,  177,  187,  173,  190,  178,  184,  195,  190,
      178,    0,  185,  197,  194,  202,  205,  194,  195,  192,
      197,  207,  198,  205,  204,    0,    0,    0,  192,  214,
      198,  217,  208,  218,  221,  210,  211,    0,  206,  203,
        0,    0,  210,  209,  225,  228,  212,  231,  221,  232,
        0,  232,  219,  224,    0,  221,  220,  236,  234,  240,

      240,  243,  242,  229,  234,  247,    0,  247,  231,  249,
      249,  252,  251,    0,  238,    0,  254,  238,    0,  255,
        0,  242,  258,  258,    0,  260,    0,  793,  284,  287,
      283,  290
    } ;

static yyconst short int yy_def[733] =
    {   0,
      728,    1,  728,  728,  728,  728,  729,  730,  728,  728,
      728,  728,  728,  728,  728,  728,  728,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  728,  728,
      728,  729,  728,  729,  730,  728,  728,  728,  728,  728,
      732,  728,  728,  728,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  729,  729,  729,  728,  732,

      728,  728,  728,  728,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  728,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      728,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  728,  731,  731,  731,  731,

      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,

      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,

      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,

      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,

      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,

      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,  731,  731,  731,
      731,  731,  731,  731,  731,  731,  731,    0,  728,  728,
      728,  728
    } ;

static yyconst short int yy_nxt[842] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,    4,   11,
       12,   11,    4,   13,   14,   15,   16,   17,    4,   18,
       19,   20,   21,   22,   18,   23,   24,   25,   26,   18,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   18,   38,   18,   18,   18,   39,   40,   43,   47,
      147,   47,   50,   52,   48,   49,   52,   51,   54,   54,
       57,   65,   44,   59,   58,   53,   60,   62,   53,   71,
      148,   63,  648,   43,   72,   66,   61,   64,   67,   73,
       76,   68,   79,   74,   77,   84,   92,   44,   80,   85,
       87,   99,   99,   88,   78,   93,   89,   90,   47,   86,

       47,  102,  102,   48,   49,   91,   96,  103,  649,  103,
      120,  121,  104,  104,   52,  122,   54,   54,  135,  138,
       97,  130,   98,   98,  136,  131,   53,  390,   43,  198,
       43,  199,  139,   99,   99,   98,  102,  102,  200,   98,
      650,   98,   44,   98,   44,  391,  151,  104,  104,  158,
      123,   96,  104,  104,  196,  202,  196,  159,  203,  104,
      104,  222,  208,  226,  209,   97,  210,   98,   98,  251,
      223,  278,  227,  104,  104,  287,  560,  279,  211,  561,
       98,  252,  351,  253,   98,  334,   98,  335,   98,  288,
      337,  352,  417,  405,  336,  406,  338,  353,  651,  354,

      584,  339,  608,  652,  653,  654,  418,  655,  585,  656,
      609,  657,  658,  660,  586,  661,  610,  662,  663,  664,
      659,  665,  666,  667,  668,  669,  670,  671,  672,  673,
      674,  675,  676,  678,  679,  680,  681,  682,  683,  684,
      677,  685,  686,  687,  688,  689,  690,  691,  692,  693,
      694,  695,  696,  697,  698,  699,  700,  701,  702,  703,
      704,  705,  706,  707,  708,  709,  710,  711,  712,  713,
      714,  715,  716,  717,  718,  719,  720,  721,  722,  723,
      724,  725,  726,  727,   42,   55,   42,   45,   45,   45,
      100,  100,  100,  647,  646,  645,  644,  643,  642,  641,

      640,  639,  638,  637,  636,  635,  634,  633,  632,  631,
      630,  629,  628,  627,  626,  625,  624,  623,  622,  621,
      620,  619,  618,  617,  616,  615,  614,  613,  612,  611,
      607,  606,  605,  604,  603,  602,  601,  600,  599,  598,
      597,  596,  595,  594,  593,  592,  591,  590,  589,  588,
      587,  583,  582,  581,  580,  579,  578,  577,  576,  575,
      574,  573,  572,  571,  570,  569,  568,  567,  566,  565,
      564,  563,  562,  559,  558,  557,  556,  555,  554,  553,
      552,  551,  550,  549,  548,  547,  546,  545,  544,  543,
      542,  541,  540,  539,  538,  537,  536,  535,  534,  533,

      532,  531,  530,  529,  528,  527,  526,  525,  524,  523,
      522,  521,  520,  519,  518,  517,  516,  515,  514,  513,
      512,  511,  510,  509,  508,  507,  506,  505,  504,  503,
      502,  501,  500,  499,  498,  497,  496,  495,  494,  493,
      492,  491,  490,  489,  488,  487,  486,  485,  484,  483,
      482,  481,  480,  479,  478,  477,  476,  475,  474,  473,
      472,  471,  470,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  460,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  436,  435,  434,  433,

      432,  431,  430,  429,  428,  427,  426,  425,  424,  423,
      422,  421,  420,  419,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  407,  404,  403,  402,  401,  400,  399,
      398,  397,  396,  395,  394,  393,  392,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,

      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  286,  285,
      284,  283,  282,  281,  280,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  225,  224,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  207,  206,  205,  204,  201,  197,

      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  157,  156,  155,  154,
      153,  152,  101,  150,  149,  146,  145,  144,  143,  142,
      141,  140,  137,  134,  133,  132,  129,  128,  127,  126,
      125,  124,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  106,  105,  101,   46,   41,
       95,   94,   83,   82,   81,   75,   70,   69,   56,   46,
       41,  728,    3,  728,  728,  728,  728,  728,  728,  728,

      728,  728,  728,  728,  728,  728,  728,  728,  728,  728,
      728,  728,  728,  728,  728,  728,  728,  728,  728,  728,
      728,  728,  728,  728,  728,  728,  728,  728,  728,  728,
      728,  728,  728,  728,  728,  728,  728,  728,  728,  728,
      728
    } ;

static yyconst short int yy_chk[842] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    7,   11,
       93,   11,   13,   14,   11,   11,   15,   13,   15,   15,
       20,   23,    7,   21,   20,   14,   21,   22,   15,   26,
       93,   22,  632,   42,   26,   23,   21,   22,   23,   27,
       29,   23,   30,   27,   29,   34,   36,   42,   30,   34,
       35,   49,   49,   35,   29,   36,   35,   35,   47,   34,

       47,   52,   52,   47,   47,   35,   44,   53,  633,   53,
       71,   71,   53,   53,   54,   72,   54,   54,   83,   85,
       44,   79,   44,   44,   83,   79,   54,  340,   96,  154,
       98,  154,   85,   99,   99,   44,  102,  102,  154,   44,
      634,   44,   96,   44,   98,  340,  102,  103,  103,  111,
       72,   97,  104,  104,  151,  156,  151,  111,  156,  151,
      151,  172,  161,  176,  161,   97,  161,   97,   97,  204,
      172,  232,  176,  196,  196,  240,  529,  232,  161,  529,
       97,  204,  303,  204,   97,  290,   97,  290,   97,  240,
      291,  303,  368,  355,  290,  355,  291,  303,  635,  303,

      558,  291,  587,  636,  637,  639,  368,  640,  558,  642,
      587,  643,  644,  645,  558,  646,  587,  647,  648,  649,
      644,  650,  651,  653,  654,  655,  656,  657,  658,  659,
      660,  661,  662,  663,  664,  665,  669,  670,  671,  672,
      662,  673,  674,  675,  676,  677,  679,  680,  683,  684,
      685,  686,  687,  688,  689,  690,  692,  693,  694,  696,
      697,  698,  699,  700,  701,  702,  703,  704,  705,  706,
      708,  709,  710,  711,  712,  713,  715,  717,  718,  720,
      722,  723,  724,  726,  729,  731,  729,  730,  730,  730,
      732,  732,  732,  630,  629,  628,  627,  626,  625,  624,

      622,  621,  620,  619,  618,  617,  616,  615,  614,  611,
      610,  609,  608,  607,  606,  605,  603,  602,  601,  600,
      599,  597,  596,  595,  594,  593,  592,  591,  590,  589,
      586,  585,  584,  581,  580,  578,  577,  576,  575,  574,
      573,  572,  571,  570,  569,  568,  565,  564,  563,  561,
      559,  557,  556,  555,  554,  551,  549,  548,  547,  546,
      545,  544,  543,  542,  541,  540,  539,  537,  536,  534,
      532,  531,  530,  528,  527,  525,  524,  523,  521,  520,
      519,  518,  517,  515,  514,  513,  512,  511,  509,  508,
      507,  506,  505,  504,  502,  501,  498,  497,  496,  495,

      493,  492,  491,  490,  489,  488,  487,  486,  484,  482,
      481,  480,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  465,  464,  463,  462,  460,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  388,  387,  386,  385,  384,

      383,  382,  381,  380,  379,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  367,  366,  365,  363,  362,  361,
      359,  358,  357,  356,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  341,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  324,  323,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  289,  288,  287,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,

      270,  269,  268,  267,  266,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  239,  238,
      237,  236,  235,  234,  233,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  213,  211,  210,  209,  208,  207,  206,  205,  203,
      202,  201,  200,  199,  198,  197,  195,  194,  192,  191,
      190,  189,  188,  187,  186,  184,  183,  182,  181,  179,
      178,  177,  174,  173,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  160,  159,  158,  157,  155,  152,

      150,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  129,
      128,  127,  126,  125,  124,  123,  121,  120,  119,  118,
      117,  116,  115,  114,  113,  112,  110,  109,  108,  107,
      106,  105,  100,   95,   94,   92,   91,   90,   89,   88,
       87,   86,   84,   82,   81,   80,   78,   77,   76,   75,
       74,   73,   70,   69,   68,   67,   66,   65,   64,   63,
       62,   61,   60,   59,   58,   57,   56,   51,   45,   41,
       38,   37,   33,   32,   31,   28,   25,   24,   19,    8,
        5,    3,  728,  728,  728,  728,  728,  728,  728,  728,

      728,  728,  728,  728,  728,  728,  728,  728,  728,  728,
      728,  728,  728,  728,  728,  728,  728,  728,  728,  728,
      728,  728,  728,  728,  728,  728,  728,  728,  728,  728,
      728,  728,  728,  728,  728,  728,  728,  728,  728,  728,
      728
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
/* $Id$ */
/* Copyright (c) 2001 Alex Hioreanu.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/* 
 * Basic lexer for use with flex (not tested with vanilla lex).  Nothing
 * very interesting here.
 *
 * Strings may not span multiple lines.  String literals may also have
 * character escapes in them, just like in C.  Numbers may not start
 * with a leading zero, since a leading zero means octal notation to
 * me, and we don't support octal/hex number literals.  A floating
 * point number can take any format as a C floating point literal.
 *
 * If flex allowed for the "non-greedy" closure operator (like every
 * modern regular expression library supplies), C-style comments could
 * be caught like this: */

#if 0 
/\*(.|\n)*?\*/ {;}
/\*(.|\n)* { printf("Unterminated comment on line %d\n", lineno); }
#endif 

/* But flex doesn't have '*?' so we have to write some inane code to
 * deal with C-style comments.
 */

#include "config.h"
#include "prefs.h"
#include "parser.h"

extern int line_number;
  
#line 846 "lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 60 "lexer.l"


#line 1000 "lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 729 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 793 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "lexer.l"
{ line_number++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "lexer.l"
{
    int c;

    for (;;) {
        while ( (c = input()) != '*' && c != EOF && c != '\n');
        if (c == '*') {
            while ( (c = input()) == '*');
            if (c == '/') break;
        } else if (c == '\n') {
            line_number++;
        } else {
            fprintf(stderr, "XWM: unterminated C-style comment on line %d\n",
                    line_number);
            break;
        }
    }
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 82 "lexer.l"
{ return TOK_DISPLAYTITLEBAR; /* ADDOPT 1: lexical symbol */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return TOK_TITLEBARFONT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return TOK_OMNIPRESENT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return TOK_DEFAULTWORKSPACE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return TOK_FOCUS_POLICY; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return TOK_ALWAYSONTOP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return TOK_ALWAYSONBOTTOM; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 89 "lexer.l"
{ return TOK_PASSFOCUSCLICK; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 90 "lexer.l"
{ return TOK_CYCLEBEHAVIOUR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return TOK_CYCLEBEHAVIOUR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return TOK_COLORTITLEBAR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return TOK_COLORTITLEBAR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return TOK_COLORTITLEBAR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return TOK_COLORTITLEBAR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return TOK_COLORTITLEBARFOCUSED; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return TOK_COLORTITLEBARFOCUSED; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return TOK_COLORTEXT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return TOK_COLORTEXT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return TOK_COLORTEXT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return TOK_COLORTEXT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return TOK_COLORTEXTFOCUSED; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return TOK_COLORTEXTFOCUSED; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return TOK_NWORKSPACES; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "lexer.l"
{ return TOK_DONTBINDMOUSE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return TOK_DONTBINDKEYS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return TOK_STICKY; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return TOK_TITLEPOSITION; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return TOK_KEEPTRANSIENTSONTOP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return TOK_SLOPPY_FOCUS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return TOK_CLICK_TO_FOCUS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return TOK_DONT_FOCUS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return TOK_SKIPCYCLE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return TOK_RAISEIMMEDIATELY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return TOK_RAISEONCYCLEFINISH; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return TOK_DONTRAISE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return TOK_DISPLAYLEFT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return TOK_DISPLAYRIGHT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return TOK_DISPLAYCENTERED; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return TOK_DONTDISPLAY; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return TOK_TRUE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return TOK_FALSE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return TOK_TRANSIENTFOR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return TOK_HASTRANSIENT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return TOK_NOT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return TOK_ISSHAPED; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return TOK_INWORKSPACE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return TOK_WINDOWNAME; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return TOK_WINDOWCLASS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return TOK_WINDOWINSTANCE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return TOK_FUNCTION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return TOK_MENU; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return TOK_BINDKEY; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return TOK_BINDBUTTON; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return TOK_BINDDRAG; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return TOK_BINDKEYRELEASE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return TOK_UNBINDKEY; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return TOK_UNBINDBUTTON; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return TOK_UNBINDDRAG; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return TOK_UNBINDKEYRELEASE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return TOK_ROOT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return TOK_FRAME; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 153 "lexer.l"
{ return TOK_TITLEBAR; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 155 "lexer.l"
{ return TOK_SENDTOWORKSPACE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 156 "lexer.l"
{ return TOK_GOTOWORKSPACE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 157 "lexer.l"
{ return TOK_CYCLENEXT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 158 "lexer.l"
{ return TOK_CYCLEPREV; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return TOK_KILLNICELY; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return TOK_KILLWITHEXTREMEPREJUDICE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 161 "lexer.l"
{ return TOK_LAUNCH; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 162 "lexer.l"
{ return TOK_FOCUS; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 163 "lexer.l"
{ return TOK_MAXIMIZE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 164 "lexer.l"
{ return TOK_MAXIMIZE_HORIZONTALLY; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 165 "lexer.l"
{ return TOK_MAXIMIZE_VERTICALLY; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 166 "lexer.l"
{ return TOK_NOP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 167 "lexer.l"
{ return TOK_QUOTE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 168 "lexer.l"
{ return TOK_MOVEINTERACTIVELY; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 169 "lexer.l"
{ return TOK_RESIZEINTERACTIVELY; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 170 "lexer.l"
{ return TOK_MOVERESIZE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 171 "lexer.l"
{ return TOK_QUIT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return TOK_BEEP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return TOK_INVOKE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 174 "lexer.l"
{ return TOK_SHOWMENU; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 175 "lexer.l"
{ return TOK_REFRESH; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 177 "lexer.l"
{ return TOK_DEFINE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 179 "lexer.l"
{ return TOK_SEMI; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 180 "lexer.l"
{ return TOK_EQUALS; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 181 "lexer.l"
{ return TOK_SET_UNCONDITIONALLY; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 182 "lexer.l"
{ return TOK_LBRACE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 183 "lexer.l"
{ return TOK_RBRACE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 184 "lexer.l"
{ return TOK_COMMA; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 185 "lexer.l"
{ return TOK_LPAREN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 186 "lexer.l"
{ return TOK_RPAREN; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 188 "lexer.l"
{
    yylval.value_string = yytext;
    return TOK_STRING;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 193 "lexer.l"
{
    yylval.value_int = atoi(yytext);
    return TOK_INTEGER;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 198 "lexer.l"
{
    yylval.value_float = (float)atof(yytext);
    return TOK_FLOAT;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 203 "lexer.l"
{line_number++;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 204 "lexer.l"
{line_number++;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 206 "lexer.l"
{;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 208 "lexer.l"
{
    fprintf(stderr, "XWM: Unrecognized keyword '%s' on line %d\n",
            yytext, line_number);
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 212 "lexer.l"
{ fprintf(stderr, "XWM: Unrecognized character '%s' on line %d\n",
            yytext, line_number); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 215 "lexer.l"
ECHO;
	YY_BREAK
#line 1627 "lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 729 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 729 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 728);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 215 "lexer.l"


int line_number = 1;

#ifndef yywrap
int yywrap()
{
    return 1;
}
#endif
